#!/usr/bin/env bash
# render-index-html.sh <site_dir> <outfile>
#
# Renders the GitHub Pages landing page: a Carbon card per area listed in
# config/areas.tsv that actually has a published report in this run
# (site_dir/<area_id>/index.html present). Adding a new area to the site
# later needs no change here — just an entry in config/areas.tsv and that
# area publishing into its own site_dir/<area_id>/ subdirectory.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
# shellcheck source=../lib/html.sh
source "${REPO_ROOT}/lib/html.sh"

SITE_DIR="${1:?usage: render-index-html.sh <site_dir> <outfile>}"
OUT_FILE="${2:?usage: render-index-html.sh <site_dir> <outfile>}"
AREAS_TSV="${REPO_ROOT}/config/areas.tsv"

if [ ! -f "$AREAS_TSV" ]; then
  echo "No areas manifest found at ${AREAS_TSV}" >&2
  exit 1
fi

INDEX_CSS='  .scenario-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(280px, 1fr)); gap: 1rem; margin-top: 1.5rem; }
  .bx--tile--clickable { text-decoration: none; color: inherit; display: block; }
  .bx--tile--clickable h3 { margin: 0 0 0.5rem; }
  .bx--tile--clickable p { margin: 0; color: #525252; }
  .intro { color: #525252; max-width: 720px; }'

{
  carbon_page_head "Quarkus Flow Exploratory" "$INDEX_CSS"

  echo "<h1>Quarkus Flow Exploratory</h1>"
  echo '<p class="intro">Automated evidence from the <a href="https://docs.quarkiverse.io/quarkus-flow/dev/">Quarkus Flow Exploratory Testing Guide</a>. Each scenario below generates a real Quarkus project, runs it, and captures logs, screenshots, and responses as evidence — pick a scenario to see its latest run.</p>'
  echo '<div class="scenario-grid">'

  tail -n +2 "$AREAS_TSV" | while IFS=$'\t' read -r area_id title description; do
    if [ -f "${SITE_DIR}/${area_id}/index.html" ]; then
      printf '<a class="bx--tile bx--tile--clickable" href="%s/"><h3>%s</h3><p>%s</p></a>\n' \
        "$area_id" "$title" "$description"
    fi
  done

  echo '</div>'

  carbon_page_footer "Generated by <a href=\"https://github.com/mcruzdev/quarkus-flow-exploratory\">quarkus-flow-exploratory</a>. Styled with <a href=\"https://carbondesignsystem.com/\">IBM Carbon</a>."
} > "$OUT_FILE"

echo "Wrote ${OUT_FILE}"
