#!/usr/bin/env bash
# render-report-html.sh <evidence_dir> <outfile>
#
# Renders a standalone HTML report from a single run's evidence directory
# (same results.tsv that SUMMARY.md is built from), for publishing to
# GitHub Pages. Not sourced by area scripts — invoked directly from CI or
# by hand.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
# shellcheck source=../lib/common.sh
source "${REPO_ROOT}/lib/common.sh"
# shellcheck source=../lib/result.sh
source "${REPO_ROOT}/lib/result.sh"

EVIDENCE_DIR="${1:?usage: render-report-html.sh <evidence_dir> <outfile>}"
OUT_FILE="${2:?usage: render-report-html.sh <evidence_dir> <outfile>}"
RESULTS_TSV="${EVIDENCE_DIR}/results.tsv"
RUN_ID="$(basename "$EVIDENCE_DIR")"

if [ ! -f "$RESULTS_TSV" ]; then
  echo "No results.tsv found in ${EVIDENCE_DIR}" >&2
  exit 1
fi

{
  cat <<'HTML'
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Quarkus Flow Exploratory — Area A Report</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
  :root { color-scheme: light dark; }
  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; max-width: 860px; margin: 2rem auto; padding: 0 1rem; line-height: 1.5; }
  table { border-collapse: collapse; width: 100%; margin: 1rem 0; }
  th, td { border: 1px solid #8884; padding: 0.5rem 0.75rem; text-align: left; vertical-align: top; }
  th { background: #8881; }
  img { max-width: 100%; border: 1px solid #8884; border-radius: 6px; }
  code { background: #8881; padding: 0.1rem 0.35rem; border-radius: 4px; }
  footer { margin-top: 2rem; font-size: 0.85rem; opacity: 0.7; }
</style>
</head>
<body>
HTML
  echo "<h1>Area A — Exploratory Run Report</h1>"
  echo "<p>Run: <code>${RUN_ID}</code><br>Generated: $(timestamp)</p>"
  echo "<table>"
  echo "<tr><th>Step</th><th>Description</th><th>Result</th><th>Note</th></tr>"
  tail -n +2 "$RESULTS_TSV" | while IFS=$'\t' read -r id desc status note; do
    printf '<tr><td>%s</td><td>%s</td><td>%s %s</td><td>%s</td></tr>\n' \
      "$id" "$desc" "$(status_emoji "$status")" "$(status_label "$status")" "$note"
  done
  echo "</table>"

  if [ -f "${EVIDENCE_DIR}/dev-ui-screenshot.png" ]; then
    echo "<h2>Dev UI Screenshot</h2>"
    echo '<img src="dev-ui-screenshot.png" alt="Quarkus Dev UI">'
  fi

  cat <<'HTML'
<h2>Result Legend</h2>
<table>
<tr><th>Result</th><th>Meaning</th></tr>
<tr><td>🟢 Passed</td><td>Expected behavior was confirmed.</td></tr>
<tr><td>🟡 Passed with observations</td><td>Main path worked, but notes, risks, or UX gaps were found.</td></tr>
<tr><td>🔴 Failed</td><td>Expected behavior did not work and needs follow-up.</td></tr>
<tr><td>⛔ Blocked</td><td>The scenario could not be completed due to environment, dependency, or access issues.</td></tr>
<tr><td>🔁 Needs follow-up</td><td>More focused testing or automation is required.</td></tr>
</table>
<footer>Generated by <a href="https://github.com/mcruzdev/quarkus-flow-exploratory">quarkus-flow-exploratory</a> — automates the <a href="https://docs.quarkiverse.io/quarkus-flow/dev/">Quarkus Flow Exploratory Testing Guide</a>, Area A.</footer>
</body>
</html>
HTML
} > "$OUT_FILE"

echo "Wrote ${OUT_FILE}"
